### ISSUE TITLE
Documentation on `eqlist` Dataset

### ISSUE THREAD

**Issue by patrickm663** [dutangc/CASdatasets#2]
Hi @dutangc 

Thank you for putting together this package!

I have found the documentation on `eqlist` to be a bit sparse, in that it doesn't really define a lot of the features like `nst`, `gap`, etc.

I have found a source that could help it be more informative to users: https://earthquake.usgs.gov/data/comcat/data-eventterms.php

I am happy to make a PR containing some updates per the source above?

Regards
Patrick

**Comment by dutangc** [comment]
Thanks for your pull-request. Due to a change in the pkg structure, I manually update the man page rather than accepting the pull-request. CD

**Comment by patrickm663** [comment]
Thanks for confirming, no problem!
